export const hotels = [
    {
        hotel : "أنجم",
        img : "asets/Img/makkah/a1.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "جبل الكعبة",
        rating : "5",
        douple : "30",
        triple : "40",
        quad : '50',
        fb : 'الحرم'
    },{
        hotel : "شيراتون",
        img : "asets/Img/makkah/a2.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "جبل الكعبة",
        rating : "5",
        douple : "30",
        triple : "40",
        quad : '50',
        fb : 'الحرم'
    },{
        hotel : "شذا مكة",
        img : "asets/Img/makkah/a3.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "جبل الكعبة",
        rating : "5",
        douple : "30",
        triple : "40",
        quad : '50',
        fb : 'الحرم'
    },{
        hotel : "ماريوت",
        img : "asets/Img/makkah/a4.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "جبل عمر",
        rating : "5",
        douple : "30",
        triple : "40",
        quad : '50',
        fb : 'الحرم'
    },{
        hotel : "فندق مكارم اجياد",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "شارع أجياد",
        rating : "5",
        douple : "30",
        triple : "40",
        quad : '50',
        fb : 'الحرم'
    },{
        hotel : "فندق الشهداء",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "شارع أجياد",
        rating : "5",
        douple : "30",
        triple : "40",
        quad : '50',
        fb : '400'
    },{
        hotel : "أبراج المريديان كدي",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "كدي",
        rating : "5",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : 'نقل'
    },{
        hotel : "كورتيارد",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "ريع بخش",
        rating : "5",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : 'نقل'
    },{
        hotel : "الماسة جراند",
        city : "مكة المكرمة",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        from : "شارع أجياد",
        rating : "4",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : '400'
    },{
        hotel : "ندى أجياد",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "شارع أجياد",
        rating : "4",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : '400'
    },{
        hotel : "الماسة دار الفائزين",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "شارع أجياد",
        rating : "5",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : '400'
    },{
        hotel : "ايلاف بكة",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "محبس الجن",
        rating : "4",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : 'نقل'
    },{
        hotel : "فندق عدنان",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "محبس الجن",
        rating : "4",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : 'نقل'
    },{
        hotel : "ضيافة الرجاء",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "ابراهيم الخليل",
        rating : "3",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : '900'
    },{
        hotel : "فندق فلسطين",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "ابراهيم الخليل",
        rating : "4",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : '900'
    },{
        hotel : "منارات الغزة",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "الغزة",
        rating : "3",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : '900'
    },{
        hotel : "فندق براديس",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "محبس الجن",
        rating : "3",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : 'نقل'
    },{
        hotel : "كدي تاور",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "ريع بخش",
        rating : "4",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : 'نقل'
    },{
        hotel : "اعمار المنار",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "ابراهيم الخليل",
        rating : "اقتصادي",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : '700'
    },{
        hotel : "درة السليمانية",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        
        city : "مكة المكرمة",
        from : "الغزة",
        rating : "اقتصادي",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : '900'
    },{
        hotel : "اركان بكة",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "محبس الجن",
        rating : "اقتصادي",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : 'نقل'
    },{
        hotel : "ابراج الكسوة",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "التيسير",
        rating : "اقتصادي",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : 'نقل'
    },{
        hotel : "ابراج التيسير",
        img : "asets/Img/makkah/kuddy.jpg",
        speach : "Situated in Makkah, within 3.5 km of Masjid Al Haram and 10 km of Hira Cave, كــــدي تــــــاور ـــ Kudi Tower features accommodation with a restaurant and free WiFi throughout the property as well as free private parking for guests who drive.",
        city : "مكة المكرمة",
        from : "التيسير",
        rating : "اقتصادي",
        douple : "50",
        triple : "70",
        quad : '110',
        fb : 'نقل'
    },
]